Repository Linaro/website, pull requests merged in 2022-05, with the labels that each got.

#1993 Create Events “2022-05-04-openeuler-developer-day”
  _posts/events/2022-05-04-openeuler-developer-day.md
  assets/images/content/openeuler-developer-day-image.png
Labels: netlify-cms/pending_publish

#1996 Update Developer Services “security”
  _services/security.md
Labels: netlify-cms/pending_publish

#1997 Update Developer Services “services”
  _services/services.md
Labels: netlify-cms/pending_publish

#1998 Update Pages “membership”
  _pages/membership.md
Labels: netlify-cms/pending_publish

#1999 Update Events “2020-12-08-linaro-virtual-connect-2021”
  _posts/events/2020-12-08-linaro-virtual-connect-2021.md
Labels: netlify-cms/pending_publish

#2000 Update Pages “events”
  _pages/events.md
Labels: netlify-cms/pending_publish

#2001 Update Blog Posts “2021-02-23-upstream-camera-support-for-qualcomm-platforms”
  _posts/current/blog/2021-02-23-upstream-camera-support-for-qualcomm-platforms.md
Labels: netlify-cms/pending_publish

#2002 Update Blog Posts “2019-12-17-python-and-go-in-the-arm-world”
  _posts/current/blog/2019-12-17-python-and-go-in-the-arm-world.md
Labels: netlify-cms/pending_publish

#2003 Update Blog Posts “2021-01-04-protected-uefi-variables-with-u-boot”
  _posts/current/blog/2021-01-04-protected-uefi-variables-with-u-boot.md
Labels: netlify-cms/pending_publish

#2004 Update Blog Posts “2019-09-26-porting-linux-to-aarch64-laptops”
  _posts/current/blog/2019-09-26-porting-linux-to-aarch64-laptops.md
Labels: netlify-cms/pending_publish

#2005 Update Blog Posts “2021-01-08-linaro-engineering-highlights-december-2020”
  _posts/current/blog/2021-01-08-linaro-engineering-highlights-december-2020.md
Labels: netlify-cms/pending_publish

#2006 Update Blog Posts “2020-04-15-aosp-on-pixel3-pocof1-running-aosp-with-mainline-kernel-on-form-factor-devices”
  _posts/current/blog/2020-04-15-aosp-on-pixel3-pocof1-running-aosp-with-mainline-kernel-on-form-factor-devices.md
Labels: netlify-cms/pending_publish

#2007 Update Pages “blog”
  _pages/blog.md
Labels: netlify-cms/pending_publish

#2008 Update Pages “team”
  _pages/team.md
Labels: netlify-cms/pending_publish

#2009 Update Blog Posts “2020-11-06-accelerating-libcamera-qcam-format-conversion-using-opengl-shaders”
  _posts/current/blog/2020-11-06-accelerating-libcamera-qcam-format-conversion-using-opengl-shaders.md
Labels: netlify-cms/pending_publish

#2010 Update Blog Posts “2020-12-14-history-of-the-interconnect-framework”
  _posts/current/blog/2020-12-14-history-of-the-interconnect-framework.md
Labels: netlify-cms/pending_publish

#2011 Update Blog Posts “2020-11-09-linaro-and-the-linux-kernel”
  _posts/current/blog/2020-11-09-linaro-and-the-linux-kernel.md
Labels: netlify-cms/pending_publish

#2012 Update Blog Posts “2020-09-24-open-on-chip-debugger-ocd-at-linaro”
  _posts/current/blog/2020-09-24-open-on-chip-debugger-ocd-at-linaro.md
Labels: netlify-cms/pending_publish

#2013 Update Blog Posts “2020-04-20-update-on-hikey-hikey960-efforts-in-aosp”
  _posts/current/blog/2020-04-20-update-on-hikey-hikey960-efforts-in-aosp.md
Labels: netlify-cms/pending_publish

#2014 Update Pages “contact”
  _pages/contact.md
Labels: netlify-cms/pending_publish

#2015 Update Events “2021-05-18-linaro-virtual-connect-2021-fall”
  _posts/events/2021-05-18-linaro-virtual-connect-2021-fall.md
Labels: netlify-cms/pending_publish

#2017 Update News Posts “2021-04-20-linaro-arm-and-qualcomm-collaborate-to-enable-native-llvm-for-windows-10-on-arm”
  _posts/current/news/2021-04-20-linaro-arm-and-qualcomm-collaborate-to-enable-native-llvm-for-windows-10-on-arm.md
Labels: netlify-cms/pending_publish

#2018 Update Pages “support”
  _pages/support.md
Labels: netlify-cms/pending_publish

#2020 Update Blog Posts “2020-08-19-force-idle-when-a-cpu-is-overheating”
  _posts/current/blog/2020-08-19-force-idle-when-a-cpu-is-overheating.md
Labels: netlify-cms/pending_publish

#2025 Update Authors “linaro”
  _authors/linaro.md
Labels: netlify-cms/pending_publish

#2026 Update Authors “linus-walleij”
  _authors/linus-walleij.md
Labels: netlify-cms/pending_publish

#2028 Update Older Posts “2013-08-26-converting-code-implementing-suspend-blockers”
  _posts/previous/2013-08-26-converting-code-implementing-suspend-blockers.md
Labels: netlify-cms/pending_publish

#2029 Update Blog Posts “2019-03-05-io-bandwidth-management-for-production-quality-services”
  _posts/current/blog/2019-03-05-io-bandwidth-management-for-production-quality-services.md
Labels: netlify-cms/pending_publish

#2030 Update Older Posts “2014-04-24-linaro-14-04-release-now-available-download”
  _posts/previous/2014-04-24-linaro-14-04-release-now-available-download.md
Labels: netlify-cms/pending_publish

#2031 Update Blog Posts “2021-04-29-linaro-developers-top-5-12-kernel-release”
  _posts/current/blog/2021-04-29-linaro-developers-top-5-12-kernel-release.md
Labels: netlify-cms/pending_publish

#2032 Update Blog Posts “2021-05-17-many-uses-of-qemu”
  _posts/current/blog/2021-05-17-many-uses-of-qemu.md
Labels: netlify-cms/pending_publish

#2033 Update Older Posts “2018-01-22-meltdown-spectre”
  _posts/previous/2018-01-22-meltdown-spectre.md
Labels: netlify-cms/pending_publish

#2034 Update Blog Posts “2020-02-06-the-end-of-an-era”
  _posts/current/blog/2020-02-06-the-end-of-an-era.md
Labels: netlify-cms/pending_publish

#2036 Update Blog Posts “2020-07-30-thermal-notifications-with-netlink”
  _posts/current/blog/2020-07-30-thermal-notifications-with-netlink.md
Labels: netlify-cms/pending_publish

#2037 Update Blog Posts “2019-09-13-what-is-linaro”
  _posts/current/blog/2019-09-13-what-is-linaro.md
Labels: netlify-cms/pending_publish

#2038 Update Older Posts “2017-04-19-whats-new-qemu-2-9”
  _posts/previous/2017-04-19-whats-new-qemu-2-9.md
Labels: netlify-cms/pending_publish

#2039 Update News Posts “2019-09-24-96boards-announces-launch-of-rockchip-rk3399-som-board”
  _posts/current/news/2019-09-24-96boards-announces-launch-of-rockchip-rk3399-som-board.md
Labels: netlify-cms/pending_publish

#2041 Update News Posts “2021-03-23-linaro-announces-launch-of-96boards-consumer-edition-specification-v2-0”
  _posts/current/news/2021-03-23-linaro-announces-launch-of-96boards-consumer-edition-specification-v2-0.md
Labels: netlify-cms/pending_publish

#2042 Update Older Posts “2011-08-12-lava-fundamentals”
  _posts/previous/2011-08-12-lava-fundamentals.md
Labels: netlify-cms/pending_publish

#2043 Update Pages “news”
  _pages/news.md
Labels: netlify-cms/pending_publish

#2044 Update Developer Services “hands_on_training”
  _services/hands_on_training.md
Labels: netlify-cms/pending_publish

#2045 Update Older Posts “2016-11-28-tee-development-with-no-hardware-is-that-possible”
  _posts/previous/2016-11-28-tee-development-with-no-hardware-is-that-possible.md
Labels: netlify-cms/pending_publish

#2047 Update Older Posts “2010-07-01-is-linaro-a-distribution”
  _posts/previous/2010-07-01-is-linaro-a-distribution.md
Labels: netlify-cms/pending_publish

#2069 Update Older Posts “2016-06-27-coresight-perf-and-the-opencsd-library”
  _posts/previous/2016-06-27-coresight-perf-and-the-opencsd-library.md
Labels: netlify-cms/pending_publish

#2070 Update Older Posts “2016-04-29-linaro-16-04-release-available-for-download-2”
  _posts/previous/2016-04-29-linaro-16-04-release-available-for-download-2.md
Labels: netlify-cms/pending_publish

#2072 Update Older Posts “2018-07-17-sve-in-qemu-linux-user”
  _posts/previous/2018-07-17-sve-in-qemu-linux-user.md
Labels: netlify-cms/pending_publish

#2074 Update Older Posts “2016-02-10-testing-a-trusted-execution-environment”
  _posts/previous/2016-02-10-testing-a-trusted-execution-environment.md
Labels: netlify-cms/pending_publish

#2099 Create Blog Posts “2022-05-10-linaro-to-present-on-embedded-ai-and-virtualization-at-embedded-world-2022”
  _posts/current/blog/2022-05-10-linaro-to-present-on-embedded-ai-and-virtualization-at-embedded-world-2022.md
Labels: netlify-cms/pending_publish

#2071 Update Older Posts “2014-09-03-op-tee-open-source-security-mass-market”
  _posts/previous/2014-09-03-op-tee-open-source-security-mass-market.md
Labels: netlify-cms/pending_publish

#2075 Update Older Posts “2013-02-05-update-android-kernel-tools”
  _posts/previous/2013-02-05-update-android-kernel-tools.md
Labels: netlify-cms/pending_publish

#2076 Update Older Posts “2014-02-03-when-will-uefi-and-acpi-be-ready-on-arm”
  _posts/previous/2014-02-03-when-will-uefi-and-acpi-be-ready-on-arm.md
Labels: netlify-cms/pending_publish

#2085 Update Older Posts “2014-09-26-arm-trustzone-qemu”
  _posts/previous/2014-09-26-arm-trustzone-qemu.md
Labels: netlify-cms/pending_publish

#2086 Update Older Posts “2015-09-18-energy-aware-scheduling-eas-progress-update”
  _posts/previous/2015-09-18-energy-aware-scheduling-eas-progress-update.md
Labels: netlify-cms/pending_publish

#2087 Update Older Posts “2016-12-16-kprobes-event-tracing-armv8”
  _posts/previous/2016-12-16-kprobes-event-tracing-armv8.md
Labels: netlify-cms/pending_publish

#2088 Update Older Posts “2016-06-16-on-the-performance-of-arm-virtualization”
  _posts/previous/2016-06-16-on-the-performance-of-arm-virtualization.md
Labels: netlify-cms/pending_publish

#2089 Update Older Posts “2016-07-29-opencsd-operation-use-library”
  _posts/previous/2016-07-29-opencsd-operation-use-library.md
Labels: netlify-cms/pending_publish

#2090 Update Older Posts “2016-09-06-stm-and-its-usage”
  _posts/previous/2016-09-06-stm-and-its-usage.md
Labels: netlify-cms/pending_publish

#2123 Update Blog Posts “2021-06-23-porting-common-linux-tools-into-morello-architecture”
  _posts/current/blog/2021-06-23-porting-common-linux-tools-into-morello-architecture.md
Labels: netlify-cms/pending_publish

#2122 Update Blog Posts “2022-03-01-how-to-build-flang-on-windows-on-arm”
  _posts/current/blog/2022-03-01-how-to-build-flang-on-windows-on-arm.md
Labels: netlify-cms/pending_publish

#2115 Update Pages “projects”
  _pages/projects.md
Labels: netlify-cms/pending_publish

#2118 Update Blog Posts “2021-06-22-ensuring-optimal-performance-through-enhanced-kernel-testing”
  _posts/current/blog/2021-06-22-ensuring-optimal-performance-through-enhanced-kernel-testing.md
Labels: netlify-cms/pending_publish

#2116 Update Older Posts “2015-09-18-energy-aware-scheduling-eas-progress-update”
  _posts/previous/2015-09-18-energy-aware-scheduling-eas-progress-update.md
Labels: netlify-cms/pending_publish

#2114 Update Events “2021-05-03-linaro-and-arm-cca-tech-day-deep-dive-into-arm-confidential-compute-architecture”
  _posts/events/2021-05-03-linaro-and-arm-cca-tech-day-deep-dive-into-arm-confidential-compute-architecture.md
Labels: netlify-cms/pending_publish

#2113 Update Pages “careers”
  _pages/careers.md
Labels: netlify-cms/pending_publish

#2111 Update Blog Posts “2020-07-21-the-evolution-of-the-qemu-translator”
  _posts/current/blog/2020-07-21-the-evolution-of-the-qemu-translator.md
Labels: netlify-cms/pending_publish

#2125 Update Blog Posts “2022-05-10-linaro-to-present-on-embedded-ai-and-virtualization-at-embedded-world-2022”
  _posts/current/blog/2022-05-10-linaro-to-present-on-embedded-ai-and-virtualization-at-embedded-world-2022.md
Labels: netlify-cms/pending_publish

#2126 Update Developer Services “qualcomm-platforms-services”
  _services/qualcomm-platforms-services.md
Labels: netlify-cms/pending_publish

#2139 Create Events “2022-05-16-embedded-world-2022”
  _posts/events/2022-05-16-embedded-world-2022.md
  assets/images/content/ew22.jpg
Labels: netlify-cms/pending_publish

#2143 Create Authors “viresh-kumar”
  _authors/viresh-kumar.md
Labels: netlify-cms/pending_publish

#2145 Create Blog Posts “2022-05-17-linaro-s-rust-based-hypervisor-agnostic-vhost-user-i2c-backend”
  _posts/current/blog/2022-05-17-linaro-s-rust-based-hypervisor-agnostic-vhost-user-i2c-backend.md
Labels: netlify-cms/pending_publish

#2142 Group membership page updates
  _includes/flow/columns.html
  _includes/flow/flow_inner.html
  _includes/membership/groups.html
  _includes/membership/related_group_members_lcg.html
  _includes/membership/related_group_members_ldcg.html
  _includes/membership/related_group_members_ledge.html
  _includes/membership/related_group_members_lite.html
  _includes/membership/related_group_members_lwg.html
  _includes/membership/related_projects_lcg.html
  _includes/membership/related_projects_ldcg.html
  _includes/membership/related_projects_ledge.html
  _includes/membership/related_projects_lite.html
  _includes/membership/related_projects_lwg.html
  _pages/group_membership.md
  admin/config.yml
  assets/css/app/membership.scss
  assets/images/content/LCG_icon_colour.svg
  assets/images/content/LCG_icon_colour_no_text.svg
  assets/images/content/LDCG_icon_colour.svg
  assets/images/content/LDCG_icon_colour_no_text.svg
  assets/images/content/LEDGE_icon_colour.svg
  assets/images/content/LEDGE_icon_colour_no_text.svg
  assets/images/content/LITE_icon_colour.svg
  assets/images/content/LITE_icon_colour_no_text.svg
  assets/images/content/LWG_icon_colour.svg
  assets/images/content/LWG_icon_colour_no_text.svg
Labels: In Progess

#2150 Update Authors “viresh-kumar”
  _authors/viresh-kumar.md
  assets/images/content/viresh-picture.jpg
Labels: netlify-cms/pending_publish

#2153 Create Events “2022-05-19-linaro-and-arm-confidential-ai-tech-event”
  _posts/events/2022-05-19-linaro-and-arm-confidential-ai-tech-event.md
Labels: netlify-cms/pending_publish

#2164 Update Events “2022-05-19-linaro-and-arm-confidential-ai-tech-event”
  _posts/events/2022-05-19-linaro-and-arm-confidential-ai-tech-event.md
Labels: netlify-cms/draft
