Repository Linaro/website, pull requests merged in 2023-10, with the labels that each got.

#3061 Create Blog Posts “2023-10-02-introducing-1-0-0-beta-release-of-windowsperf-visual-studio-extension”
  _posts/current/blog/2023-10-02-introducing-1-0-0-beta-release-of-windowsperf-visual-studio-extension.md
  assets/images/content/configuring-the-sampling-parameters.png
  assets/images/content/implementing-code-adjustments-1.png
  assets/images/content/implementing-code-adjustments-2.png
Labels: netlify-cms/pending_publish

#3062 Update Blog Posts “2023-10-02-introducing-1-0-0-beta-release-of-windowsperf-visual-studio-extension”
  _posts/current/blog/2023-10-02-introducing-1-0-0-beta-release-of-windowsperf-visual-studio-extension.md
Labels: netlify-cms/pending_publish

#3063 Create Blog Posts “2023-10-05-android-14-now-available-on-linaro-reference-boards-in-aosp”
  _posts/current/blog/2023-10-05-android-14-now-available-on-linaro-reference-boards-in-aosp.md
  assets/images/content/image-of-hikey960-running-android-14.png
  assets/images/content/image-of-rb5-running-android-14.png
  assets/images/content/screenshot-2023-10-05-at-11.34.24.png
Labels: netlify-cms/pending_review

#3065 Update Blog Posts “2023-10-05-android-14-now-available-on-linaro-reference-boards-in-aosp”
  _posts/current/blog/2023-10-05-android-14-now-available-on-linaro-reference-boards-in-aosp.md
  assets/images/content/image-of-hikey960-running-android-14.jpg
  assets/images/content/image-of-rb5-running-android-14.jpg
Labels: netlify-cms/pending_review

#3067 Create Authors “prathamesh-kulkarni”
  _authors/prathamesh-kulkarni.md
Labels: netlify-cms/pending_publish

#3066 Create Blog Posts “2023-10-09-improvements-to-gcc-s-code-gen-for-vector-initialization-on-aarch64”
  _posts/current/blog/2023-10-09-improvements-to-gcc-s-code-gen-for-vector-initialization-on-aarch64.md
  assets/images/content/improvements-to-gcc-s-code-gen-for-vector-initialization-on-aarch64.png
Labels: netlify-cms/pending_publish

#3068 Update Blog Posts “2023-10-09-improvements-to-gcc-s-code-gen-for-vector-initialization-on-aarch64”
  _posts/current/blog/2023-10-09-improvements-to-gcc-s-code-gen-for-vector-initialization-on-aarch64.md
Labels: netlify-cms/pending_publish

#3069 Update Blog Posts “2023-10-09-improvements-to-gcc-s-code-gen-for-vector-initialization-on-aarch64”
  _posts/current/blog/2023-10-09-improvements-to-gcc-s-code-gen-for-vector-initialization-on-aarch64.md
Labels: netlify-cms/pending_publish

#3070 Update Team Members “team”
  _data/team.json
Labels: netlify-cms/draft

#3073 Create Authors “maxim-uvarov”
  _authors/maxim-uvarov.md
  assets/images/content/maxim-uvarov.png
Labels: netlify-cms/pending_publish

#3072 Create Blog Posts “2023-10-17-ledge-blogs-uefi-http-and-https-boot-in-u-boot”
  _posts/current/blog/2023-10-17-ledge-blogs-uefi-http-and-https-boot-in-u-boot.md
  assets/images/content/gnu-grub-version-2.12~rc1-7.png
  assets/images/content/istock-860653830sm.jpg
Labels: netlify-cms/pending_publish

#3074 Update Blog Posts “2023-10-17-ledge-blogs-uefi-http-and-https-boot-in-u-boot”
  _posts/current/blog/2023-10-17-ledge-blogs-uefi-http-and-https-boot-in-u-boot.md
Labels: netlify-cms/pending_publish

#3075 Update Blog Posts “2023-10-17-ledge-blogs-uefi-http-and-https-boot-in-u-boot”
  _posts/current/blog/2023-10-17-ledge-blogs-uefi-http-and-https-boot-in-u-boot.md
Labels: netlify-cms/pending_publish

#3076 Update Blog Posts “2023-10-17-ledge-blogs-uefi-http-and-https-boot-in-u-boot”
  _posts/current/blog/2023-10-17-ledge-blogs-uefi-http-and-https-boot-in-u-boot.md
Labels: netlify-cms/pending_publish

#3077 Create Blog Posts “2023-10-18-tracking-code-size-variations-between-llvm-releases”
  _posts/current/blog/2023-10-18-tracking-code-size-variations-between-llvm-releases.md
  assets/images/content/figure-1-evolution-of-code-size-aarch64-.png
  assets/images/content/figure-2-evolution-of-code-size-x86_64-.png
  assets/images/content/figure-3-evolution-of-code-size-fixed-aarch64-.png
  assets/images/content/figure-4-commits-impacting-code-size-aarch64-.png
  assets/images/content/figure-5-impact-of-inlining-flags-on-deepsjeng-.png
  assets/images/content/figure-6-impact-of-optimization-flags-on-aosp.png
  assets/images/content/figure-7-code-size-for-inline-threshold-values.png
  assets/images/content/figure-8-lnt-dashboard-14-.png
Labels: netlify-cms/pending_publish

#3078 Create Authors “antoine-moynault”
  _authors/antoine-moynault.md
  assets/images/content/antoine-moynault.jpg
Labels: netlify-cms/pending_publish

#3079 Update Blog Posts “2023-10-18-tracking-code-size-variations-between-llvm-releases”
  _posts/current/blog/2023-10-18-tracking-code-size-variations-between-llvm-releases.md
Labels: netlify-cms/pending_publish

#3080 Update Blog Posts “2023-10-18-tracking-code-size-variations-between-llvm-releases”
  _posts/current/blog/2023-10-18-tracking-code-size-variations-between-llvm-releases.md
Labels: netlify-cms/pending_publish

#3082 Update Blog Posts “2023-08-30-windowsperf-release-2-5-1”
  _posts/current/blog/2023-08-30-windowsperf-release-2-5-1.md
Labels: netlify-cms/pending_publish

#3083 Update Blog Posts “2023-10-02-introducing-1-0-0-beta-release-of-windowsperf-visual-studio-extension”
  _posts/current/blog/2023-10-02-introducing-1-0-0-beta-release-of-windowsperf-visual-studio-extension.md
Labels: netlify-cms/pending_publish

#3084 Update Blog Posts “2023-09-04-introducing-the-windowsperf-gui-the-visual-studio-2022-extension”
  _posts/current/blog/2023-09-04-introducing-the-windowsperf-gui-the-visual-studio-2022-extension.md
Labels: netlify-cms/pending_publish

#3085 Update Blog Posts “2023-06-08-windowsperf-release-2-4-0-introduces-the-first-stable-version-of-sampling-model-support”
  _posts/current/blog/2023-06-08-windowsperf-release-2-4-0-introduces-the-first-stable-version-of-sampling-model-support.md
Labels: netlify-cms/pending_publish

#3086 Create Blog Posts “2023-10-23-windowsperf-release-3-0-0”
  _posts/current/blog/2023-10-23-windowsperf-release-3-0-0.md
  assets/images/content/istock-1220974008_sm.jpg
Labels: netlify-cms/pending_publish

#3087 Update Blog Posts “2023-10-23-windowsperf-release-3-0-0”
  _posts/current/blog/2023-10-23-windowsperf-release-3-0-0.md
Labels: netlify-cms/pending_publish

#3088 Update Blog Posts “2023-10-23-windowsperf-release-3-0-0”
  _posts/current/blog/2023-10-23-windowsperf-release-3-0-0.md
Labels: netlify-cms/pending_publish

#3091 Update Blog Posts “2023-10-26-upstream-linux-support-now-available-for-the-the-qualcomm-snapdragon-8-gen-3-mobile-platform”
  _posts/current/blog/2023-10-26-upstream-linux-support-now-available-for-the-the-qualcomm-snapdragon-8-gen-3-mobile-platform.md
Labels: netlify-cms/pending_publish

#3092 Update Blog Posts “2023-10-26-upstream-linux-support-now-available-for-the-the-qualcomm-snapdragon-8-gen-3-mobile-platform”
  _posts/current/blog/2023-10-26-upstream-linux-support-now-available-for-the-the-qualcomm-snapdragon-8-gen-3-mobile-platform.md
Labels: netlify-cms/pending_publish
